name: Deploy Docs 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies for docs
      run: |
        pip install -r docs/requirements.txt

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Convert selected Jupyter notebooks to markdown and copy to docs
      run: |
        notebooks=("quick_start" "Co2_adorption_MOF" "peptide-hemolytic" "surfactant-cmc" "docking_GNINA_vs_AutoDockVina" "inverse_design")
        for notebook in "${notebooks[@]}"; do
          jupyter nbconvert --to markdown "examples/${notebook}.ipynb"
          cp "examples/${notebook}.md" "docs/source/${notebook}.md"
        done

    - name: Build the documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: docs/build/html
        commit_message: "Deploy documentation: ${{ github.sha }}"
