name: Deploy Docs 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies for docs
      run: |
        pip install -r docs/requirements.txt

    - name: Build the documentation
      run: |
        sudo apt-get install pandoc
        jupyter nbconvert --to markdown examples/quick_start.ipynb
        cp examples/quick_start.md docs/source/quick_start.md
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: docs/build/html
        commit_message: "Deploy documentation: ${{ github.sha }}"
